### ISSUE TITLE
Freeze to black in Mario Sports Superstars (EUR) 0004000000188D00 

### ISSUE THREAD

**Issue by Korados** [JourneyOver/CTRPF-AR-CHEAT-CODES#49]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x] Other

## Description
When I try to access the Tennis or Golf mode of Mario Sports Superstars (EUR)
while the CTRPF plugin is activated, the game freezes to black. I tried both Action Replay files and
I also tried placeing the plugin separately into an ActionReplay folder but this didn't work.
The other three sports in the game work normally. I assume that it has something to do
with the Tennis and Golf parts being developed by Camelot. Is there a workaround for this?

Thank you for your help!

**Comment by JourneyOver** [comment]
I honestly couldn't say, I'm not the one who made the action replays nor any of the codes, it could be many various things that bring about this issue, all I could say is either test with taking random cheats out for said game and see if you can pinpoint if it's a code issue, or if it's a action replay issue.

I'll be able to fix it by removing the broken codes if it's a code issue (once I get my new computer) but since I'm not the one who made the action replay stuff I won't be able to do anything about it if it comes down to it being just an action replay issue.

**Comment by Korados** [comment]
I'm pretty sure it's an error of the Action Replay because even if I enter the game without any codes but just the AR, the game crashes when I try to play Tennis of Golf. Who actually made the AR? Maybe I can talk to them about it.

**Comment by JourneyOver** [comment]
Nanquitas made it, you can find him on gbatemp.

**Comment by JourneyOver** [comment]
I'm going to go ahead and close this since it's an issue with the plug-in and not any of the codes.
