### ISSUE TITLE
Gateway Cheats - Some Codes for various Games are not working

### ISSUE THREAD

**Issue by Smoker1** [JourneyOver/CTRPF-AR-CHEAT-CODES#60]
## Checklist:

- [x] Broken Cheat
- [x] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Description

Codes worked perfectly under the Gateway System. However, under Luma/Rosalina, there are Codes that will not work. Codes will have to either be Refound, or the System needs to be Updated to get the Gateway Cheats working Properly.

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]
N3DS

**3DS Firmware Version:** [e.g. 11.6.0-39E]
Latest Luma/Rosalina

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]
Both

**Game Version:** [e.g. 1.0, 1.1]
Version for Cheats

**Language & Region:** [e.g. English & USA]
US or EU

**Comment by JourneyOver** [comment]
a few things

1. I do not make the codes as I do not know how
2. 99% of the codes in this DB are from fort42
3. Any and all updates to this DB are reliant mainly on pull requests.
4. I'm not the one who makes luma/rosalina, so I can't do nothing about them not working under luma/rosalina.
5. This repo is for CTRPF and action replay codes, mixed with a bit of gateshark due to to the fact that I handle sharkives DB as well.

and also, your issue doesn't explain what games or anything are broken, you can't expect me to read your mind..and no I am not going to sit here and test literally every single game under the sun for broken codes.
