### ISSUE TITLE
Cheats for Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey (00040000001D1500)

### ISSUE THREAD

**Issue by Conan179** [JourneyOver/CTRPF-AR-CHEAT-CODES#64]
## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x ] Other

## Description
I hope so right now. I looking for Cheats for Mario & Luigi: Bowser's Inside Story + Bowser Jr.'s Journey (00040000001D1500).
Has any body Codes for the Game?

## Extra Information (only need to fill in if issuing for Broken Cheats)
**New3DS XL:**

**11.9.0-24E** 
**LUMAS3DS 9.0 Plugin Loader** 

**Ver. 1.1**

**German EU**

**Comment by JourneyOver** [comment]
Sorry I am not a creator of codes, just a compiler of codes. If you find the codes somewhere you are free to point them to me (with a url or whatever) and I will gladly add them to the database, otherwise unless I find the codes myself scouring the web (which right now my time is very limited so the chances of me looking right now are very slim) then they might not be added unless someone comes along and makes a Pull Request with said codes.
