### ISSUE TITLE
Reveal map code that doesn't make you invincible?

### ISSUE THREAD

**Issue by Flyingboots29** [JourneyOver/CTRPF-AR-CHEAT-CODES#70]
Hello is there a version of the Reveal Map code that doesn't make you invincible as well? Thanks in advance!

## Checklist:

- [ ] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [x] Other

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** [e.g. 1.0, 1.1]

**Language & Region:** [e.g. English & USA]

**Comment by JourneyOver** [comment]
1. Idk what game you are even talking about, since you didn't mention the game anywhere nor did you fill out the issue template at all..

2. Even if I did know what game you are talking about, I'm not really sure if there is a code out there that does such a thing, I don't really have time much anymore to really look around for codes and on top of that I do not create codes either. So if you are wanting something added to the DB, you'll either need to find it yourself or create it yourself and make a Pull Request to get it added to the DB.
